### ISSUE TITLE
Display All Sections from a Page in Wikipedia

### ISSUE THREAD

**Issue by shefik** [9bitStudios/wikiblurb#4]
Is there a way to display all sections from a page in Wikipedia?

Right now, the default setting (type `all`) only seems to display the `inbox`, along with content from the first section `0`.

Also, is there a way to calculate the count for the total number of sections a page has?

**Comment by 9bitStudios** [comment]
I will have to look into this. A cursory search seems to indicate that the API pushes you towards returning individual sections but there might be a way.

**Comment by shefik** [comment]
@9bitStudios The count might be possible by counting the number of `<h2>` tags, based on the selector `.mw-content-text h2`.

**Comment by mrtnc** [comment]
I want to display all sections of a Wikipedia page. Is that possible?

**Comment by 9bitStudios** [comment]
Yes this is possible if you remove "section" from the query string for the API call.
