### ISSUE TITLE
special page not working

### ISSUE THREAD

**Issue by 15emedoctor** [9bitStudios/wikiblurb#8]
Hello,

I do i get this to work for this page https://en.wikipedia.org/wiki/Special:Nearby ?

Thanks

**Comment by 9bitStudios** [comment]
Hi there 15emedoctor -- Getting data from that location is definitely not officially supported at the moment. I'd have to look into whether it's even possible to get data from that sort of resource via the API.

**Comment by 9bitStudios** [comment]
This does not appear to be supported in using the Wikipedia API.
