### ISSUE TITLE
issue to load infobox

### ISSUE THREAD

**Issue by tonarii** [9bitStudios/wikiblurb#9]
Hello, thanks a lot for your script.
I found it when i was looking for a way to display wiki infobox. :)
But i have an issue to load infobox on my page.
I can display the "text", but when i change type: 'text' to type: 'infobox' and don't see anything.
Can you help me with that ?
Thanks.
Regards.

**Comment by 9bitStudios** [comment]
Hi there -- Sorry for the delay in response here. I have finally gotten around to pushing out some fixes to the script that are possibly related. In the current package example calling the plugin like so in index.html... 

```javascript
$('#article').wikiblurb({type: 'infobox'});
```

will properly display the infobox for the default demo page. Let me know if you still have issues. Thanks!
